### ISSUE TITLE
scale the chart up when filtering out certain fee levels

### ISSUE THREAD

**Issue by Giszmo** [jhoenicke/mempool#1]
It would be nice if the chart spaced was used better when filtering out low fee transactions.

For example when I filter for transactions above 200sat/B, only the bottom 20% of the chart are used.

**Comment by jhoenicke** [comment]
I think this is a bug in flot. But I can probably work around it, by removing the fee levels instead of setting the visibility flag to false.

Needs a bit of rewrite though, to keep the data somewhere else.

**Comment by jhoenicke** [comment]
Should work now.

**Comment by Giszmo** [comment]
it does :) thank you
