### ISSUE TITLE
Suggestion: Making the colors closer in shades to make quick lookup faster

### ISSUE THREAD

**Issue by Transisto** [jhoenicke/mempool#12]
I don't think as many people need to lookup precisely the color to fee range in the chart.

I feel like there is about 5 similar shades of blue that repeat multiple time, I think going 

![image](https://user-images.githubusercontent.com/388716/32669536-de6f945a-c60e-11e7-812c-53205a06472b.png)

I feel like repeating twice the RGB spectrum at two tones my be enouth to differentiate clearly the interval for those who care this much.

**Comment by jhoenicke** [comment]
As you probably noticed I'm not good in choosing nice colors.  If you have an idea for a nice color scheme feel free to make a pull request.

Procedure to test locally:

First, clone the repository on your computer (or download it).  Then download [24h.js](https://jochen-hoenicke.de/queue/24h.js), [1w.js](https://jochen-hoenicke.de/queue/1w.js), [all.js](https://jochen-hoenicke.de/queue/all.js) from the website and save into the directory `web/queue`.  Open mempool.js in an editor.  Add the following lines around line 335  (function `button`).  The `+` marks the new lines.

```
+function call(data) {
+    loadData(data);
+}
 function button(timespan) {
+       var script = document.createElement("script");
+       script.src = timespan + ".js";
+       document.head.appendChild(script);
```

Now you can open the file index.html in your browser and the corresponding buttons `24h`, `1w`, `all` should work.

Change the colors in the beginning of `mempool.js` (given in `#RRGGBB` format).  Under Linux/Windows use Ctrl+F5 to refresh the page.  The colors are only 66 % opaque; you can change that in line 212.

Test with different time scales.  I prefer to have a dark color as top color to get a better contrast for the top line of the chart.

**Comment by jhoenicke** [comment]
I guess the trick is fewer colors, see https://test.jochen-hoenicke.de/queue/#30d

I made the gaps more regular with roughly 40 % increment for each level.
