### ISSUE TITLE
donation address text doesn't match donation address href

### ISSUE THREAD

**Issue by dooglus** [jhoenicke/mempool#13]
Page text says:

> Donation Bitcoin: bc1ql4rl5lh2tuunt3jd75nymzdffgm6yaml8kkrmw (Segwit)

but it links to:

> bitcoin:3BXqhoLBCBdUGxTbrkBVmkedmGgJ4wNpsg

Are those two different addresses? Do they both work? Is there a better one to use? Bitcoin Core accepts them both as valid destinations.

**Comment by jhoenicke** [comment]
Both work, but I guess the bc1 address is not so widely supported yet, so I should probably use the 3BX address instead.  I'm impressed that Bitcoin Core supports it.  I thought bech32 support was scheduled for 0.15.2.

**Comment by dooglus** [comment]
Oh, I'm running a recent master branch version of Core which could be why it accepts the bech32 address. I'll try sending a tip to the bc1 address later today, but agree that it would be better not to show it until they are more widely known and/or accepted.

**Comment by jhoenicke** [comment]
> I'm running a recent master branch version of Core

That explains it.  The bech32 code was merged in October to master.

I reverted the text now to the backwards compatible address.
