### ISSUE TITLE
CPFP/Parent not Considered

### ISSUE THREAD

**Issue by TheBlueMatt** [jhoenicke/mempool#15]
Ignoring ancestorfees and descendantfees provides a potentially very incomplete look at the mempool's feerates - as a rough approximation of "effective feerate" of a transaction, you might consider doing max((ancestorfees + descendantfees)/(ancestorsize + descendantsize), min(fee/size, ancestorfees/ancestorsize)).

This avoids listing high-fee transactions which depend on many low-fee ancestors as high-fee, as well as allows transactions which have been CPFP'd to be listed as higher "effective feerate", at least modulo trying to figure out what the "real" "effective feerate" of a transaction is by exploring which descendant (groups) are higher feerate.

This would be especially useful for the "Mempool size" view, which some people use to select feerates on their transactions.

**Comment by jhoenicke** [comment]
I just changed it (14:28 UTC) for the non-backup server.  The effect is small but noticable.

It looks like both ancestorfees and descendantfees contain current tx fee, so I subtracted the latter in the first term:

```
	$tfpb = ($afees + $dfees - $fee) / ($asize + $dsize - $size);
	$fpb = $fee / $size;
	$afpb = $afees / $asize;
	$feeperbyte = max($tfpb, min($fpb, $afpb));
```

**Comment by TheBlueMatt** [comment]
Cool, indeed, thanks for catching my bug :).
