### ISSUE TITLE
show node parameters

### ISSUE THREAD

**Issue by Giszmo** [jhoenicke/mempool#2]
It would be nice to see what the configured maximum mempool size was at any given time. Maybe as a red line in the chart.

**Comment by jhoenicke** [comment]
Problem is that the maximum mempool size depends on the transaction mix (small transaction take more space than large transaction).

Maybe one can plot the fraction of memory filled, something like http://statoshi.info/dashboard/db/memory-pool?panelId=1&fullscreen&from=1492366590656&to=1494958590657

**Comment by jhoenicke** [comment]
Given that a full mempool seems to be happen very seldomly, I don't think it is worth to add a visualisation for this. So I close this for now.
