### ISSUE TITLE
Fee ranges aren't as useful as before.

### ISSUE THREAD

**Issue by Transisto** [jhoenicke/mempool#23]
![image](https://user-images.githubusercontent.com/388716/34252142-693c0bce-e610-11e7-9075-7cd27d423bf5.png)

There used to have way more ranges, now 5 of the ranges that are left, 1,2,5,10... sat/byte have the same amount of transaction and size.

**Comment by jhoenicke** [comment]
You can select one of the "more stripes" servers on the top tab.   I plan
to use the large, more stripes scheme for logging in the future, which has
roughly 20% steps between each stripe.
