### ISSUE TITLE
Confusing text on web page

### ISSUE THREAD

**Issue by dooglus** [jhoenicke/mempool#29]
Towards the end of the page I see:

> You can also click in the legend to toggle the visibility of the total fee statistics.

I have been unable to find anywhere I can click in the legend that toggles visibility of anything. I see I can click on different fee levels there to remove low fee bands from the display, but I think this sentence is talking about something else.

Am I just missing it, or is the text wrong?

**Comment by jhoenicke** [comment]
This was for the previous version which didn't have the "by-fee" view in a separate graph.  The text is outdated now.  I removed it from the live versions.  I still have to update the version in the repository, but probably will do it together with the pending change for more fee bands.
