### ISSUE TITLE
bottom band not displayed

### ISSUE THREAD

**Issue by dooglus** [jhoenicke/mempool#30]
On the legend I see a color is defined for tx that pay "0-1" sat/B, but I never see a band of that color in the charts.

It might be better not to show that range in the legend if the color isn't used in the chart.

**Comment by nicolas17** [comment]
I do see a gray band. Was this fixed?

**Comment by jhoenicke** [comment]
It depends on the node config (whether it accepts tx below 1sat/byte), and of course the remaining network (whether someone sent a tx and whether it was propagated).  I like to keep that option, so it's easy to check if there are any transactions or not.

The gray band is still not displayed by default.  You have to enable it explicitly in the legend.
