### ISSUE TITLE
Consider having <1 sat/B fees on BCH be its own color on your site

### ISSUE THREAD

**Issue by cculianu** [jhoenicke/mempool#35]
Hi,

Not sure if this is the appropriate place but people on reddit are wondering what is up with the BCH mempool and lots of people rely on your site for visualizing it.

Right now there's a backlog of <1 sat/B tx's in the BCH mempool and your categorization code bins all of them in the 0-5 range.

Perhaps it would be helpful to the community if you were to color code <1 sat/B tx's differently and bin them together so users can quickly see the "stress test" tx's filling up the mempool versus the actual real tx's?

Thanks!

**Comment by morrisonbrett** [comment]
Or, remove alt-coins and have the site only support Bitcoin. For every alt-coin will be a unique set of issues.

**Comment by cculianu** [comment]
But Bitcoin Cash is Bitcoin. 🥇

**Comment by jhoenicke** [comment]
I switched to my other server, which is separating this information.  The first server needs a database upgrade, which is always a bit tricky.  It doesn't see the very cheap transactions, though, so I need to check why later.

https://test.jochen-hoenicke.de/queue/  has both servers.

**Comment by jhoenicke** [comment]
I switched to my other server, which is separating this information.  The first server needs a database upgrade, which is always a bit tricky.  It doesn't see the very cheap transactions, though, so I need to check why later.

https://test.jochen-hoenicke.de/queue/  has both servers.

**Comment by jhoenicke** [comment]
I switched to my other server, which is separating this information.  The first server needs a database upgrade, which is always a bit tricky.  It doesn't see the very cheap transactions, though, so I need to check why later.

https://test.jochen-hoenicke.de/queue/  has both servers.

**Comment by jhoenicke** [comment]
I switched to my other server, which is separating this information.  The first server needs a database upgrade, which is always a bit tricky.  It doesn't see the very cheap transactions, though, so I need to check why later.

https://test.jochen-hoenicke.de/queue/  has both servers.

**Comment by jhoenicke** [comment]
I switched to my other server, which is separating this information.  The first server needs a database upgrade, which is always a bit tricky.  It doesn't see the very cheap transactions, though, so I need to check why later.

https://test.jochen-hoenicke.de/queue/  has both servers.

**Comment by jhoenicke** [comment]
I switched to my other server, which is separating this information.  The first server needs a database upgrade, which is always a bit tricky.  The other doesn't see the very cheap transactions, though.  I guess these transaction are not very well propagated.  They both run with 1 sat/kB min fee.

https://test.jochen-hoenicke.de/queue/  has both servers.

Edit: Sorry for spamming, the server was always telling me that it couldn't sent the message, but it appears it got through anyway.

**Comment by cculianu** [comment]
RE Spamming: ha ha, it happens. 

Thank you man for switching over.. like you said I guess these tx's didn't make it into the mempool. 
 Anyway I'm glad you switched over to more fine-grained color coding.  Hopefully it'll come in handy for everyone. We all love your site! Thanks for maintaining it!

Oh by the way we added official OP_RETURN support to Electron Cash (rather than the old hackish method).. I say this because you expressed interest in being able to do OP_RETURN tx's.
