### ISSUE TITLE
add amount to lightning donations

### ISSUE THREAD

**Issue by ppachur** [jhoenicke/mempool#37]
Several wallets (such as Zap / Zap iOS, LND via lncli) will not let you modify the amount contained in a lightning payment-request, which will then default to 0 satoshis.

You should therefore either add a default amount (say 5k or 10k satoshis, multiple donations are cheap) or even better add different options or a form to ask the user how much he/she would like to donate (in satoshis) before creating the payment-request.

The easy solution would be to just add an amount when creating the invoice (web/lnd/invoice-mp.py:39). :)

**Comment by jhoenicke** [comment]
I'll probably add a third tab where you can set the amount and maybe even the memo text.

**Comment by ppachur** [comment]
That would be great. I was about to implement it myself an make a pr, but I already spent too much time to get the python setup to run. :)

**Comment by jhoenicke** [comment]
Implemented by https://github.com/jhoenicke/mempool/commit/e5458cc1646174f814094bbf16f33272f6956411
