### ISSUE TITLE
Illegal division by zero at mempool-sql.pl line 30

### ISSUE THREAD

**Issue by coretechs** [jhoenicke/mempool#38]
Trying to get this running using Bitcoin v0.17 and I keep running into the following error:

Illegal division by zero at mempool-sql.pl line 30, <> line 8.

The getrawmempool RPC call in v0.17 returns a new property "fees" that appears to have broken the mempool-sql.pl script. The script runs without error if the "fees" property is removed from the output.

**Comment by jarole** [comment]
hi @coretechs . How did you remove fee from the output?

**Comment by jhoenicke** [comment]
I have to look how to make the parser more robust or use a perl JSON library and see if the overhead is okay.  We could also use `jq` to filter the input.
