### ISSUE TITLE
Chart in Bitcoin value

### ISSUE THREAD

**Issue by prusnak** [jhoenicke/mempool#4]
Would it be possible to create third type of chart - which would show value of Bitcoins transacted? (i.e. not total fee like you show on hover, but total coins transacted)

**Comment by jhoenicke** [comment]
It's not something `getrawmempool` outputs.  I think parsing the raw transactions would just take too much resources to be run every minute.

Unless there is a simple way to compute that from startingpriority and currentpriority...
