### ISSUE TITLE
BTC (default mempool) displays upside down

### ISSUE THREAD

**Issue by blatherdrift** [jhoenicke/mempool#40]
Hello! 

I cloned your git and set everything up but when I click 'btc (default mempool)' it shows an upside chart that goes into the negative. Any idea what's up?

I'm not sure where this data is being pulled from. I assume my own node? It's being run off apache2 on ubuntu 18.04 lts.

**Comment by jhoenicke** [comment]
Sorry, for not replaying.  Note that you need to change mempool.js (the config array in the beginning) to include your server.  Make sure that "ranges" matches the feelimit array in the mempool-sql script, change the "colors" and "show" arrays as you like.

Usually the reason for negative values is setting the "inc" option wrong.  It should be true for newer scripts.
