### ISSUE TITLE
Most important graph is last on the page.

### ISSUE THREAD

**Issue by Transisto** [jhoenicke/mempool#41]
Both "Unconfirmed transaction count" and "Pending transaction fees" can be manipulated to show very different chart.

A 500KB transaction would barely show in the transaction count.

200MB worth of 1 Sat/byte would create a big spike on the total fee chart without being that relevant.

We use this tool to estimate the best transaction fee so we're always and only checking the last graph. "Mempool size"

**Comment by NiExTy** [comment]
Completely agree I came here to suggest the same. "Mempool Size in MB" should be on the top.

**Comment by Transisto** [comment]
Fixed
