### ISSUE TITLE
install - mkdata.sh doesn't work correctly because mempool.log not present yet.

### ISSUE THREAD

**Issue by benwilliams** [jhoenicke/mempool#44]
When following the install instructions, mempool.log doesn't exist so all the *.js files are not setup correctly. Shows errors:

cat: mempool.log: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
tail: cannot open 'mempool.log' for reading: No such file or directory
./mkdata.sh: line 8: mempool.log: No such file or directory

**Comment by giannucci** [comment]
I'm having the same issue, please let me know if you figured it out.

**Comment by resipsadude** [comment]
You are using a version of `bitcoin-cli` which changed the output of `bitcoin-cli getrawmempool true` from "size" to "vsize".  So change lines 22-23 in `mempool_sql.py` to:

   if "vsize" in obj:
        size = obj["vsize"]

Sorry for my super late response.  Just saw your issue.

**Comment by jhoenicke** [comment]
I think this can be closed now. The `vsize` issue was fixed a while ago.
