### ISSUE TITLE
"total" does not make sense in "mempool size in MB" chart

### ISSUE THREAD

**Issue by ratpoison4** [jhoenicke/mempool#46]
![image](https://user-images.githubusercontent.com/53399252/73997389-5879fe00-492c-11ea-9227-0062d7df047a.png)

1+, 2+ and so on are cumulative values. "Total" is the sum of sums. Should be equivalent of 0+ (not sure fee<1 is technically even possible in BTC). On the screenshot "Total" must be ~ 1.4M and not 4M.

**Comment by jhoenicke** [comment]
No total is 0+.  There are some 0-1 fee transactions, which depending on the configuration may not be shown by default.
