### ISSUE TITLE
[REQ] Ethereum mempool tracker

### ISSUE THREAD

**Issue by brianddk** [jhoenicke/mempool#55]
I notice you have an ETH donation address.  Have you considered adding ETH as one of the supported coins (BTC, BCH, BSV, DASH)?

**Comment by jhoenicke** [comment]
Considered yes, especially as zengo already did most of the work.  I just have to set a full node up myself and adapt their code to work side-by-side with my page.

You can use their site: https://txpool.zengo.com/#0,24h

**Comment by jhoenicke** [comment]
Ethereum statistics is online.
