### ISSUE TITLE
No Core node?

### ISSUE THREAD

**Issue by snavsenv** [jhoenicke/mempool#6]
Hi, i i think the site is pretty interesting. But i was wondering why there is not a Core node?

I can only choose between SegWit2x UASF and CASH. I think the Core node is the most interesting.

**Comment by jhoenicke** [comment]
Now that UASF didn't fork off I will rename that to Core (or NO2x) soon.
At the moment Segwit2x, UASF, and Core behave identically.

**Comment by schildbach** [comment]
This issue seems to be fixed.
