### ISSUE TITLE
Option to show only the top 100mb in the graph

### ISSUE THREAD

**Issue by Transisto** [jhoenicke/mempool#65]
If graphing the whole 300mb default mempool makes the 1mb drops almost impossible to see.

If someone is placing it's transaction 100mb away from tip, It's expected to take at least a full month before it confirms.

**Comment by jhoenicke** [comment]
Displaying only the top 100 mb would make the graph look very strange, similar to what the default mempool graph shows.  I think it is better to filter by fee level to get a better view of the interesting part.

I have changed the default view for BTC to dismiss below 5 sat/b.  Although, that needs to be regularly updated to reflect the current situation.

**Comment by Transisto** [comment]
Very good implementation!, I like that everything sub-5 sat is still available in the mouse-over panel.
A dynamic way to implement this would be to only show section that fits 100mb.

![image](https://user-images.githubusercontent.com/388716/112725686-e679c500-8eef-11eb-8697-482dd1b28afe.png)

In the example above 3 sats and below would be trimmed out as they **currently** sum to more than 100mb

100mb is still very conservative, personally I'd be good with blocks that make up to next ~50mb
