### ISSUE TITLE
Watermark the chart

### ISSUE THREAD

**Issue by Giszmo** [jhoenicke/mempool#72]
Screenshots are the most common way of sharing this service. Those should always contain either the displaying website or this github repo discretely overlaid somewhere.

**Comment by jhoenicke** [comment]
It's a good idea.  I started experimenting with jflot.watermark.  I stil have to see if I like the position and size of the watermark.

Here is a preview: https://test.jochen-hoenicke.de/queue

**Comment by Giszmo** [comment]
You probably don't want the text where there is "action". I suspect top left, right of the legend is least likely to contain data points.

**Comment by jhoenicke** [comment]
Yes, but I feel the center is good for that.  If there is a backlog (see ETH), the action is usually at the top and if there is little action, the bottom may be so cluttered that the watermark isn't visible.
The logo is in the background, so it shouldn't hide lines (the areas are transparent, so the logo is visible through them).

**Comment by jhoenicke** [comment]
On second thought, I changed the position of the logo to top right. I tried with a different scales and its very uncommon, that the graph will go all the way to the top.  And even if it does, the graph will just cover the logo a bit.  The graph will still be clear.

Top left doesn't work out of the box (it's hidden behind the legend) and I like the corner better then top center.
