### ISSUE TITLE
LNURL donation QR not working. Rerurns 404

### ISSUE THREAD

**Issue by anton-isidore** [jhoenicke/mempool#78]
Cannot donate via LNURL on the page. Invoice generation works.

But LNURL fails with error 404

**Comment by jhoenicke** [comment]
Thanks, for the info.  I'm looking into it.  One problem was that the well-known record pointed to an old url that didn't survive the server upgrade last June.  I currently still get an error after fixing this.  I'm not sure if this is due to caching, or if there is another wrong url somewhere.

**Comment by jhoenicke** [comment]
Tried again and it works fine now.
