### ISSUE TITLE
Separate 0 fee transactions

### ISSUE THREAD

**Issue by jhmartin** [jhoenicke/mempool#8]
The lowest band is 0-5. Consider a bottom band of 0 and then 1-5 above it; this will highlight the amount of 0-fee spam.

**Comment by schildbach** [comment]
That would leave a hole between 0 (exclusive) and 1 (exclusive). You'd need to introduce a 0-1 band instead. But I guess the 0-5 band serves the "spam purpose" very well already.

**Comment by jhoenicke** [comment]
Actually, I don't include zero-fee transaction at all. I think 0.0001-5 already serves the purpose of capturing the low fee transactions as Andreas said.  Many "low-fee spam" is around 1 sat/byte and probably would be included in an 1-5 band.
