### ISSUE TITLE
Switching y-axis units from kB to mB for memory pool size plot

### ISSUE THREAD

**Issue by dhimmel** [jhoenicke/mempool#9]
Great visulations at [Johoe's Mempool Statistics](https://core.jochen-hoenicke.de/queue/#24h)!

Have you considered using ~~millibytes~~ megabytes (mB) rather than kilobytes (kB) for the memory pool figure:

![mempool-size](https://user-images.githubusercontent.com/1117703/31579127-49df8424-b0fd-11e7-8ba8-8453eb44080a.png)

This will make it easier to mentally estimate how many blocks would be required to clear the entire mempool. It also seems like the mempool is often now in the range of multiple megabytes.

**Comment by jhoenicke** [comment]
Hmm, you probably meant megabytes (funny typo).   I don't see a real need; the difference is just "," vs. "." in the tooltip.  Okay the numbers on the left hand side would be smaller.

**Comment by dhimmel** [comment]
Commas on y-axis, i.e. by passing the y-axis tick labels through [`toLocaleString`](https://docs.microsoft.com/en-us/scripting/javascript/reference/tolocalestring-number) would probably also satisfy me... I guess the main issue I'm trying to address is being able to effortlessly convert from y-axis to number of blocks needed to clear the mempool to a certain fee level. Without any separation, its hard to read the numbers.
